---
name: Verify Images
on:
  pull_request:
    branches:
      - main

env:
  REPO: "ghcr.io/coreruleset/albedo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Build images
        uses: docker/bake-action@v4.1.0
        with:
          files: |
            ./docker-bake.hcl
          targets: default
          set: |
            *.platform=linux/amd64
          load: true
          push: false

      - name: Run container
        run: |
          echo "Starting container"
          docker run --pull "never" -d --name albedo-test "${REPO}:0"
          docker logs albedo-test

      - name: Verify container
        run: |
          [ $(docker inspect albedo-test --format='{{.State.Running}}') = 'true' ]
